/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as YearByYearRouteImport } from './routes/year-by-year'
import { Route as PerformancesRouteImport } from './routes/performances'
import { Route as CapacityRevenueRouteImport } from './routes/capacity-revenue'
import { Route as IndexRouteImport } from './routes/index'

const YearByYearRoute = YearByYearRouteImport.update({
  id: '/year-by-year',
  path: '/year-by-year',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformancesRoute = PerformancesRouteImport.update({
  id: '/performances',
  path: '/performances',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRevenueRoute = CapacityRevenueRouteImport.update({
  id: '/capacity-revenue',
  path: '/capacity-revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capacity-revenue': typeof CapacityRevenueRoute
  '/performances': typeof PerformancesRoute
  '/year-by-year': typeof YearByYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capacity-revenue': typeof CapacityRevenueRoute
  '/performances': typeof PerformancesRoute
  '/year-by-year': typeof YearByYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capacity-revenue': typeof CapacityRevenueRoute
  '/performances': typeof PerformancesRoute
  '/year-by-year': typeof YearByYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/capacity-revenue' | '/performances' | '/year-by-year'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/capacity-revenue' | '/performances' | '/year-by-year'
  id: '__root__' | '/' | '/capacity-revenue' | '/performances' | '/year-by-year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapacityRevenueRoute: typeof CapacityRevenueRoute
  PerformancesRoute: typeof PerformancesRoute
  YearByYearRoute: typeof YearByYearRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/year-by-year': {
      id: '/year-by-year'
      path: '/year-by-year'
      fullPath: '/year-by-year'
      preLoaderRoute: typeof YearByYearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performances': {
      id: '/performances'
      path: '/performances'
      fullPath: '/performances'
      preLoaderRoute: typeof PerformancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity-revenue': {
      id: '/capacity-revenue'
      path: '/capacity-revenue'
      fullPath: '/capacity-revenue'
      preLoaderRoute: typeof CapacityRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapacityRevenueRoute: CapacityRevenueRoute,
  PerformancesRoute: PerformancesRoute,
  YearByYearRoute: YearByYearRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
